# Generated by Django 3.2.8 on 2021-10-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20211007_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_d',
            new_name='user',
        ),
    ]
