# Generated by Django 3.2.8 on 2021-10-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_user_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='borrowed_books',
        ),
        migrations.CreateModel(
            name='BorredBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.userinfo')),
            ],
        ),
    ]
