# Generated by Django 3.2.8 on 2021-10-08 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211008_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorredBooks',
            new_name='BorredBook',
        ),
    ]
