# Generated by Django 3.2.8 on 2021-10-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20211009_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
